name: Docker2
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: build homedir.tar.gz
      run: |
        pwd
        cd usrhomedir
        tar -zcvf ../homedir.tar .
        cd ..
        gzip homedir.tar

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mane1docker/alpine-custom:latest
